# Generated by Django 4.0.1 on 2022-02-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='licence_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
